language: python
python:
  - "3.7"
stages:
  - execute

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: execute
      name: "Running the Script"
      script: python hello-world-requirements.py